language: python
python:
  - "2.6"
  - "2.7"

addons:
  postgresql: "9.3"

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y node-less

install:
  - make install

script:
  - make test

notifications:
  email: false
