language: python
python:
  - "2.6"
  - "2.7"

addons:
  postgresql: "9.3"

before_install:
    - npm install -g less
    - sudo su postgres -c "psql template1 -c \"create user test with encrypted password 'aPassword' superuser\""

install:
  - ./scripts/build.sh

script:
  - make test

notifications:
  email: false
