language: python
python:
  - "2.6"

env:
  - BUILD_VERSION=100 secure: "3Gk7fQEwGx6rZZFWQWh8WnQ0qvm8oDtapZvqBtQgMCozPw3X6cTKkjEOj/v/AAZ6EpEOepJ7gxs6+n6zSbybrO5qcredshoxeEhduSiDr7Fa3qUiA6RF7qPDn3BU4EqSHDJlrvekm8AR2jh/bJK1hJNkHDSDp8ul868GIKIkk44="

addons:
  postgresql: "9.3"

services:
  - rabbitmq
  - memcached
  - elasticsearch

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y npm libxml2-dev libxslt1-dev
  - wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-0.90.13.deb
  - sudo dpkg -i elasticsearch-0.90.13.deb
  - sudo service elasticsearch restart
  - npm install -g less
  - sudo ln -s /usr/local/lib/node_modules/less/bin/lessc /usr/local/bin
  - sed -i 's:jenkins-pg92:localhost:' config/alembic.ini-dist
  - sudo apt-get install rubygems ruby-dev gcc
  - sudo gem install fpm

install: true

before_script:
    - psql -c "create user test with encrypted password 'aPassword' superuser;" -U postgres
    - psql -c 'create database socorro_test;' -U postgres
    - psql -c 'create database socorro_integration_test;' -U postgres
    - psql -c 'create database socorro_migration_test;' -U postgres

script:
  - BUILD_TYPE=rpm
  - make package

after_script:
  - curl -T socorro-${BUILD_VERSION}-1.x86_64.rpm -ubramwelt:${BINTRAY_API_KEY} https://api.bintray.com/content/bramwelt/rpm/socorro/${BUILD_VERSION}/socorro-${BUILD_VERSION}.x86_64.rpm
